# Generated by Django 2.2.6 on 2019-12-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('firstOccupaion', models.TextField()),
                ('secondOccupation', models.TextField()),
                ('pageTittle', models.TextField()),
            ],
        ),
    ]
