# Generated by Django 2.2.6 on 2019-12-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioTemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutH1', models.CharField(max_length=40000)),
                ('describeYourSelf', models.TextField()),
                ('aboutImage', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=40000)),
                ('aboutProject', models.CharField(max_length=40000)),
                ('projectImageOne', models.ImageField(blank=True, upload_to='profile_image')),
                ('projecImageTwo', models.ImageField(blank=True, upload_to='profile_image')),
                ('projectImageThree', models.ImageField(blank=True, upload_to='profile_image')),
                ('projectImageFour', models.ImageField(blank=True, upload_to='profile_image')),
                ('projectImageFive', models.ImageField(blank=True, upload_to='profile_image')),
                ('projectLink', models.CharField(max_length=40000)),
            ],
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='firstOccupaion',
            field=models.CharField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='pageTittle',
            field=models.CharField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='secondOccupation',
            field=models.CharField(max_length=40000),
        ),
    ]
