# Generated by Django 2.2.6 on 2019-12-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioTemplate', '0002_auto_20191212_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='aboutProject',
            field=models.TextField(),
        ),
    ]
