# Generated by Django 2.2.6 on 2019-11-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliaTemplate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTechnologyUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnology_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
