# Generated by Django 2.2.6 on 2019-11-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliaTemplate', '0002_projecttechnologyused'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDescription',
        ),
        migrations.DeleteModel(
            name='ProjectTechnologyUsed',
        ),
    ]
