# Generated by Django 2.2.6 on 2019-11-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexModel',
            new_name='Model',
        ),
    ]
