# Generated by Django 2.2.6 on 2019-11-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioSite', '0002_auto_20191116_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=100)),
                ('ganguages', models.CharField(max_length=200)),
                ('gitHub_link', models.CharField(max_length=300)),
            ],
        ),
    ]
